include:
    # Metadata shared by many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml

    # OS builds
    - local: .gitlab/os-jvm.yml


# NOTE: It’s possible to overwrite a globally defined before_script or after_script with per-job actions
# Deploy host gradle.properties to the root of the repo
# CI_GRADLE_PROPERTIES_PATH is set in runner config
default:
  before_script:
    - echo $CI_GRADLE_PROPERTIES_PATH
    - cp -v -p $CI_GRADLE_PROPERTIES_PATH .

stages:
    - Test SDK
    - Build Sample
    - Publish To Maven

############################################## pipeline jobs

buildSample:debug:
  extends:
    - .conf:env
    - .conf:debug
    - .conf:artifacts
    - .conf:runner:tags
    - .conf:rule:default
    - .buildSample:do

publishToMaven:release:
  extends:
    - .conf:env
    - .conf:release
    - .conf:runner:tags
    - .conf:rule:release
    - .publishToMaven:do

testSDK:release:
  extends:
    - .conf:env
    - .conf:release
    - .conf:runner:tags
    - .conf:rule:default
    - .testSDK:do